FROM node:16 AS builder

WORKDIR /usr/src/app

# 复制其余源代码到工作目录
COPY . .

# 安装依赖
RUN npm install --registry=https://registry.npm.taobao.org && npm install nodemon -g --save-dev


# 暴露你的服务所需的端口，这里使用的是 8082
EXPOSE 8082

# 设置启动命令为你的应用的启动命令
CMD [ "nodemon", "main.js" ]

